repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=70, --target-version=py310]

    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]